name: my-example-config
common:
  pythonCommand: python3
  pythonVersion: 3.9.10
components:
  - name: baseSubscriber
    path: components/baseSubscriber
    program: ros2 run baseSubscriber
    restartOnError: true
  - name: basePublisher
    path: components/basePublisher
    program: ros2 run basePublisher
